name: Build Docker Container

on:
  push:
    tags:        
      - '*'       

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return ${GITHUB_REF/refs\/tags\//};
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ergoregion/armadillo_build_tools:${{ steps.tag.outputs.result }}